model: stackspot-ai
model-settings-file: .aider.model.settings.yml
model-metadata-file: .aider.model.metadata.json
git: true
gitignore: true
auto-commits: true
dirty-commits: true
attribute-author: true
attribute-committer: true
pretty: true
stream: true
verbose: false

# Configuração centralizada de logging
logging:
  level: INFO  # Nível global de log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      enabled: true
      level: INFO
    file:
      enabled: true
      level: INFO
      filename: "aider.log"
  # Configuração por componente
  components:
    litellm:
      level: INFO
    repomap:
      level: INFO
    commands:
      level: INFO
    watch:
      level: INFO
    main:
      level: INFO
    stackspot:
      level: INFO
    providers:
      level: INFO
  # Configuração de módulos de terceiros
  disable_existing_loggers: true  # Importante para desabilitar loggers existentes
  loggers:
    httpx:
      level: WARNING  # Aumentando para WARNING para suprimir mensagens de DEBUG
    asyncio:
      level: WARNING
    watchfiles:
      level: WARNING
    watchdog:
      level: WARNING
    urllib3:
      level: WARNING
    pydantic:
      level: WARNING 