- name: stackspot-ai
  edit_format: diff
  use_repo_map: true
  send_undo_reply: true
  examples_as_sys_msg: true
  reminder: user
  extra_params:
    max_tokens: 8192
    model_type: code
    streaming: true
    temperature: 0.7
    api_base: https://genai-code-buddy-api.stackspot.com
    api_path: /v1/code/completions
