- name: stackspot-ai
  edit_format: diff
  use_repo_map: true
  send_undo_reply: true
  examples_as_sys_msg: true
  reminder: user
  max_tokens: 8192
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  streaming: true
  max_chat_history_tokens: 1024
  extra_params:
    model_type: code
    api_base: https://genai-code-buddy-api.stackspot.com
    api_path: /v1/chat/completions

- name: stackspot-ai-chat
  edit_format: diff
  use_repo_map: true
  send_undo_reply: true
  examples_as_sys_msg: true
  reminder: user
  max_tokens: 8192
  temperature: 0.7
  streaming: true
  extra_params:
    model_type: chat
    api_base: https://genai-code-buddy-api.stackspot.com
    api_path: /v1/chat/completions

- name: stackspot-ai-code
  edit_format: diff
  use_repo_map: true
  send_undo_reply: true
  examples_as_sys_msg: true
  reminder: user
  max_tokens: 8192
  temperature: 0.7
  streaming: true
  extra_params:
    model_type: code
    api_base: https://genai-code-buddy-api.stackspot.com
    api_path: /v1/code/completions

- name: stackspot-ai-assistant
  edit_format: diff
  use_repo_map: true
  send_undo_reply: true
  examples_as_sys_msg: true
  reminder: user
  max_tokens: 8192
  temperature: 0.7
  streaming: true
  extra_params:
    model_type: assistant
    api_base: https://genai-code-buddy-api.stackspot.com
    api_path: /v1/assistant/completions
