litellm_settings:
  drop_params: true
  api_base: "https://genai-code-buddy-api.stackspot.com"
  cache: false
  request_timeout: 60
  retry: true
  retry_status_codes: [429, 500, 502, 503, 504]
  max_retries: 3
  stream_chunk_size: 50
  max_tokens: 8192
  temperature: 0.7
  metadata:
    user: "aider"
    purpose: "code-assistant"

providers:
  stackspot:
    api_base: "https://genai-code-buddy-api.stackspot.com"
    api_key: "${STACKSPOTAI_CLIENT_KEY}"
    client_id: "${STACKSPOTAI_CLIENT_ID}"
    client_realm: "${STACKSPOTAI_REALM}"
    models:
      stackspot-ai:
        provider: stackspot
        model: stackspot-ai
        max_tokens: 8192
        max_input_tokens: 16384
        max_output_tokens: 8192
        model_type: code
        streaming: true
        temperature: 0.7
      stackspot-ai-chat:
        provider: stackspot
        model: stackspot-ai-chat
        max_tokens: 8192
        max_input_tokens: 16384
        max_output_tokens: 8192
        model_type: chat
        streaming: true
        temperature: 0.7
      stackspot-ai-code:
        provider: stackspot
        model: stackspot-ai-code
        max_tokens: 8192
        max_input_tokens: 16384
        max_output_tokens: 8192
        model_type: code
        streaming: true
        temperature: 0.7
      stackspot-ai-assistant:
        provider: stackspot
        model: stackspot-ai-assistant
        max_tokens: 8192
        max_input_tokens: 16384
        max_output_tokens: 8192
        model_type: chat
        streaming: true
        temperature: 0.7 